# Interactive component

<script src="https://d3js.org/d3.v6.js"></script>

<div id="main">
<div style="text-align:center;">
<h2>2019-2020 Capital Bikeshare Daily Usage Trend</h2>
</div>
<div id="filter-box" class="filter-box" style="text-align:center;">
<select id="year-list">
<option value="all">all</option>
<option value="2019">2019</option>
<option value="2020">2020</option>
</select>
<span class="legend registered">registered</span>
<span class="legend casual">casual</span>
<span class="legend total">total</span>
</div>
<div id="chart" style="text-align:center;"></div>
</div>

<script src="data.js"></script>   

<script src="bike.js"></script>

In 2019, most bike-sharing activities took place between March to October, in other words, between Spring to early Fall, among which Spring is the peak season users tend to engage in the bike-sharing, with daily average rental amount approaching to 15,000.

Under the impact of the pandemic, 2020 witnessed a sharp decline of total rental amount and the trend tends to be more oscillating. Since May, the amount of registered users decreased while casual users increased.

This plot also helps solidifying our interpretation of the four days with peak bike sharing rides. By selecting "all" for years, "casual" and "total" for the type of users. We can find that those two lines have the same four peak days as identified in chapter 5. Some of the visitors for the cherry blossom come from different cities and states, and therefore being a casual users for the local bike sharing company. For the BLM protest and the president election celebration, there are also a large portion of participants who come from nearby cities. Therefore, the line of casual and total users are sharing the same peak days.


