# Conclusion

## Limitations

Since the weather data fetched from freemeteo.com is a daily-based data set instead of an hourly-based records, we are not able to analyze and observe the trends in a more detailed scale. If possible, data set with date accurate to hour could be exploited and therefore, daily trend of bike-sharing service could be analyzed.

There is another question that we really interested in but are not able to explore, due to the limitation of data provided by the Capital Bikeshare Company. We would like to see that on a person to person level if casual users become subscribed members throughout year 2019 to 2020. However, the Capital Bikeshare Company only provides identification numbers for trips rather than users, so for now there is no way for us to identify the users to a person to person base.

## Lessons Learned

By handling a data set with 5 million observations and 9 features, we learned how to clean and transform the extremely large data set and finally saved it as a data frame with 701 entries and 11 total columns. The whole algorithm takes about an hour to run each time, and therefore tells us how important it is to check all details after we make any changes.

## Future Directions

Using our methodology, a trend analysis of competitors operating in business model analogous with Capital Bikeshare could be conducted to explore the similarities and differences for further concerns.

The bike sharing company could also explore distinctive characteristics or outliers implicit in dataset based on resulting plots, and conduct Attribution Analysis and provide the data-driven advises or strategies for future service improvement.

